# /etc/calamares/modules/netinstall.conf
---
groupsUrl:
  - file:///usr/local/share/netinstallbasic.yaml
  - file:///usr/local/share/netinstall-core.yaml
  - file:///usr/local/share/netinstall-apps.yaml
required: false
