# config/includes.chroot/etc/calamares/settings.conf
---
modules-search: [ local ]

instances:
  - id:       offline
    module:   packages
    config:   packages.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partitions
    - netinstall
    - users
    - summary
  - exec:
    - partitions
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - packages@offline
    - shellprocess@deploy
    - umount
  - show:
    - finished

branding: debian
prompt-on-logout: true
