# config/includes.chroot/etc/calamares/modules/welcome.conf
---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true
requirements:
    requiredStorage:    15.0
    requiredRam:        2.0
    internetCheckUrl:   http:gnewsense.sourceforge.io
    check:
        - storage
        - ram
        - power
        - internet
    required:
        - storage
        - ram
